"""
Report Generator Module
Auto-generates professional pentest/security reports in Markdown and HTML.
"""

import os
from datetime import datetime
from kadeai.utils.logger import setup_logger

logger = setup_logger("kadeai.report_generator")


class ReportGeneratorModule:
    def __init__(self, config: dict):
        self.reports_dir = config.get("REPORTS_DIR", "reports/")
        os.makedirs(self.reports_dir, exist_ok=True)

    async def execute(self, action: str, params: dict) -> str:
        actions = {
            "pentest_report": self.pentest_report,
            "executive_summary": self.executive_summary,
        }
        fn = actions.get(action)
        if not fn:
            return f"[report_generator] Unknown action: {action}"
        return await fn(params)

    async def pentest_report(self, params: dict) -> str:
        target = params.get("target", "Unknown Target")
        findings = params.get("findings", [])
        tester = params.get("tester", "KadeAI")
        date = datetime.now().strftime("%Y-%m-%d")
        filename = f"pentest_{target.replace('.', '_')}_{date}.md"
        path = os.path.join(self.reports_dir, filename)

        severity_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
        findings_md = []
        for i, f in enumerate(findings, 1):
            sev = f.get("severity", "Info")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
            icon = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢", "Info": "⚪"}.get(sev, "⚪")
            findings_md.append(f"""
### {i}. {f.get('title', 'Untitled Finding')}

| Field | Value |
|---|---|
| Severity | {icon} {sev} |
| CVSS | {f.get('cvss', 'N/A')} |
| Affected | {f.get('affected', target)} |

**Description:** {f.get('description', 'N/A')}

**Evidence:** {f.get('evidence', 'N/A')}

**Recommendation:** {f.get('recommendation', 'N/A')}
""")

        report = f"""# Penetration Test Report

| | |
|---|---|
| **Target** | {target} |
| **Date** | {date} |
| **Tester** | {tester} |
| **Classification** | CONFIDENTIAL |

---

## Executive Summary

This report presents the findings of a penetration test conducted against **{target}**.
The assessment identified **{len(findings)}** finding(s) across various severity levels.

| Severity | Count |
|---|---|
| 🔴 Critical | {severity_counts['Critical']} |
| 🟠 High | {severity_counts['High']} |
| 🟡 Medium | {severity_counts['Medium']} |
| 🟢 Low | {severity_counts['Low']} |
| ⚪ Info | {severity_counts['Info']} |

---

## Findings

{"".join(findings_md) if findings_md else "_No findings recorded. Add findings via the report module._"}

---

## Methodology

Testing was performed following industry-standard methodologies including OWASP Testing Guide and PTES.

---

_Report generated by KadeAI on {date}_
"""

        with open(path, "w") as f:
            f.write(report)

        logger.info(f"Report saved: {path}")
        return f"[report_generator] Pentest report saved to: {path}"

    async def executive_summary(self, params: dict) -> str:
        target = params.get("target", "Unknown")
        critical = params.get("critical", 0)
        high = params.get("high", 0)
        medium = params.get("medium", 0)
        low = params.get("low", 0)
        date = datetime.now().strftime("%Y-%m-%d")

        total = critical + high + medium + low
        risk = "Critical" if critical > 0 else "High" if high > 0 else "Medium" if medium > 0 else "Low"

        summary = f"""
[Report Generator] Executive Summary for {target} ({date})
{'='*55}
Overall Risk: {risk}
Total Findings: {total}

  🔴 Critical : {critical}
  🟠 High     : {high}
  🟡 Medium   : {medium}
  🟢 Low      : {low}

{'⚠️  IMMEDIATE ACTION REQUIRED — Critical vulnerabilities present.' if critical > 0 else ''}
{'Remediation should be prioritized within 30 days.' if high > 0 else ''}
"""
        return summary
